feat: dont allow commits to main branch

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,24 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+# Colors
+red='\033[0;31m'
+no_color='\033[0m'
+
+# Get current branch
+curr_branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [[ "$curr_branch" =~ main ]]; then
+  echo -e "${red}You can't commit directly to "$curr_branch".${no_color}"
+  echo ""
+  echo "Commits to main branch arent allowed."
+  echo ""
+  exit 2
+fi
+
 echo " --- "
 echo " "
 echo "Running ESlint..."
 echo " "
 npm run lint
-
 echo " --- "
